name: deploy-toy-website-environments
concurrency: toy-company

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  # Lint the Bicep file.
  lint:
    uses: garima2510/Bicep-Environments/.github/workflows/lint.yml@main

  # Deploy to the test environment.
  deploy-test:
    uses: garima2510/Bicep-Environments/.github/workflows/deploy.yml@main
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: rg-test
      reviewApiUrl: https://sandbox.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: garima2510/Bicep-Environments/.github/workflows/deploy.yml@main
    needs: deploy-test
    with:
      environmentType: Production
      resourceGroupName: rg-prod
      reviewApiUrl: https://api.contoso.com/reviews
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}